### ISSUE TITLE
Call to self causes an error

### ISSUE THREAD

**Issue by LenaKM** [ddietze/Py-Hardware-Support#1]
I'm trying to use the uc480 module with ThorCam.
I get a `NameError: name 'self' is not defined` from the line `img = self.cam.acquire()` in the script from your [documentation](http://ddietze.github.io/Py-Hardware-Support/uc480.html).

Is there a simple way around this?

Removing the 'self' gives a `uc480Error: Error: uc480 function call failed! Error code = 3 in function is_InitCamera`.

**Comment by LenaKM** [comment]
I've managed to fix this by removing the 'self' and adding the uc480 folder to the system path (you get an import error from the Ipython console on some machines without this).

```
#add module folder to path to get around import error
import sys
sys.path.append('C:/Users/Lena/pythonscripts/uc480')


import uc480
import pylab as pl


# create instance and connect to library
cam = uc480.uc480()

# connect to first available camera
cam.connect()

# take a single image
img = cam.acquire()

# clean up
cam.disconnect()

pl.imshow(img)
pl.show()
```

Somehow this gets around the `is_InitCamera` error vs. adding that folder to the sys path outside of the script.

This module is a lifesaver after trying and failing with various USB and webcam control modules which simply don't work with Thorcam CMOS cameras. 

![pythonthorcam](https://cloud.githubusercontent.com/assets/15944726/20669590/f2443f3e-b56c-11e6-825c-91831d8d7f4c.png)



Works well. Cheers!

**Comment by ddietze** [comment]
Hi Lena,
glad to hear that it works for you!
The error '3' is a generic error that is issued by the uc480 library when it cannot connect to a camera (IS_CANT_OPEN_DEVICE). From what I understand, it seems that this is a library issue and not connected to loading the python module and files. Therefore, I don't quite understand why adding the path actually did resolve this issue. Any ideas welcome! Maybe I can add this as a bugfix to the code..
Thanks and cheers,
Daniel
